# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.6 on 2016-06-11 02:57
=======
# Generated by Django 1.9.6 on 2016-06-11 03:08
>>>>>>> 4774cf26f239c43fec2cb316d448a20fa927182c
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='all_name',
        ),
    ]
