# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160514_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='trivial',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
